{
    'name': '3PL Logistic Company',
    'version': '18.0.1.1',
    'category': 'Inventory/Logistics',
    'summary': '3PL Warehouse Services: multi-client, portal access, automated billing, own-truck delivery',
    'author': 'Custom',
    'depends': [
        'stock',
        'sale_management',
        'sale_service',
        'purchase',
        'portal',
        'account',
        'product',
        'barcodes',
        'stock_barcodes',
        'delivery',
        'stock_delivery',
        'delivery_driver',
        'delivery_carrier_manual_weight',
        'delivery_price_method',
        'stock_picking_report_delivery_cost',
    ],
    'data': [
        'security/ir.model.access.csv',
        'data/product_data.xml',
        'data/fee_rate_data.xml',
        'data/stock_location_data.xml',
        'data/automation.xml',
        'data/cron.xml',
        'data/delivery_carrier_data.xml',
        'views/tpl_fee_rate_views.xml',
        'views/tpl_client_rate_views.xml',
        'views/tpl_stock_history_views.xml',
        'views/stock_location_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/stock_picking_views.xml',
        'views/tpl_delivery_rate_views.xml',
        'views/delivery_carrier_views.xml',
        'views/stock_picking_delivery_views.xml',
        'views/warehouse_map_views.xml',
        'views/truck_map_views.xml',
        'views/account_move_views.xml',
        'views/tpl_report_views.xml',
        'views/menus.xml',
        'portal/portal_templates.xml',
        'views/tpl_api_key_views.xml',
    ],
    'assets': {
        'tpl_3pl_logistic.assets_portal_css': [
            'tpl_3pl_logistic/static/src/css/tpl_portal.css',
        ],
        'web.assets_backend': [
            'tpl_3pl_logistic/static/src/css/warehouse_map.css',
            'tpl_3pl_logistic/static/src/xml/warehouse_map.xml',
            'tpl_3pl_logistic/static/src/js/warehouse_map.js',
            'tpl_3pl_logistic/static/src/css/truck_map.css',
            'tpl_3pl_logistic/static/src/xml/truck_map.xml',
            'tpl_3pl_logistic/static/src/js/truck_map.js',
        ],
    },
    'license': 'LGPL-3',
    'installable': True,
    'application': True,
    'auto_install': False,
}
